### ISSUE TITLE
Unable to lint new version of cocoapod

### ISSUE THREAD

**Issue by syky27** [JSSAlertView/JSSAlertView#52]
```
─syky at aluminium in ~/Desktop/test/JSSAlertView on swift3✔ using ‹2.2.4›
╰─± pod lib lint JSSAlertView.podspec --verbose

    JSSAlertView (3.0.0) - Analyzing on iOS 8.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `JSSAlertView` from `/Users/syky/Desktop/test/JSSAlertView`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A JSSAlertView

Downloading dependencies

-> Installing JSSAlertView (3.0.0)
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `JSSAlertView` iOS 8.0
      - Generating Info.plist file at `../../../../../private/var/folders/ww/gjw6wvt95mxd8y1r4k10vj5h0000gn/T/CocoaPods/Lint/Pods/Target Support Files/JSSAlertView/Info.plist`
      - Generating module map file at `../../../../../private/var/folders/ww/gjw6wvt95mxd8y1r4k10vj5h0000gn/T/CocoaPods/Lint/Pods/Target Support Files/JSSAlertView/JSSAlertView.modulemap`
      - Generating umbrella header at `../../../../../private/var/folders/ww/gjw6wvt95mxd8y1r4k10vj5h0000gn/T/CocoaPods/Lint/Pods/Target Support Files/JSSAlertView/JSSAlertView-umbrella.h`
    - Installing target `Pods-App` iOS 8.0
      - Generating Info.plist file at `../../../../../private/var/folders/ww/gjw6wvt95mxd8y1r4k10vj5h0000gn/T/CocoaPods/Lint/Pods/Target Support Files/Pods-App/Info.plist`
      - Generating module map file at `../../../../../private/var/folders/ww/gjw6wvt95mxd8y1r4k10vj5h0000gn/T/CocoaPods/Lint/Pods/Target Support Files/Pods-App/Pods-App.modulemap`
      - Generating umbrella header at `../../../../../private/var/folders/ww/gjw6wvt95mxd8y1r4k10vj5h0000gn/T/CocoaPods/Lint/Pods/Target Support Files/Pods-App/Pods-App-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to `../../../../../private/var/folders/ww/gjw6wvt95mxd8y1r4k10vj5h0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj`
  - Writing Lockfile in `../../../../../var/folders/ww/gjw6wvt95mxd8y1r4k10vj5h0000gn/T/CocoaPods/Lint/Podfile.lock`
  - Writing Manifest in `../../../../../private/var/folders/ww/gjw6wvt95mxd8y1r4k10vj5h0000gn/T/CocoaPods/Lint/Pods/Manifest.lock`

Integrating client project

[!] Please close any current Xcode sessions and use `App.xcworkspace` for this project from now on.

Integrating target `Pods-App` (`../../../../../var/folders/ww/gjw6wvt95mxd8y1r4k10vj5h0000gn/T/CocoaPods/Lint/App.xcodeproj` project)
  Adding Build Phase '[CP] Embed Pods Frameworks' to project.
  Adding Build Phase '[CP] Copy Pods Resources' to project.
  Adding Build Phase '[CP] Check Pods Manifest.lock' to project.
  - Running post install hooks
  Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with xcodebuild.
xcodebuild clean build -workspace App.xcworkspace -scheme App -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination id=DCE2D8E3-0F6B-4593-BBCC-A907101A7DD6
2016-09-27 22:27:41.815 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeMultiEdit.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.815 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeColors.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.816 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XAlign.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.816 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.816 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.816 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.817 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMQuickHelp.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.817 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KZLinkedConsole.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.817 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/HighlightSelectedString.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.817 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/GitDiff.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.818 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Cichlid.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.818 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-09-27 22:27:41.818 xcodebuild[27821:12622528] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AdjustFontSize.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Build settings from command line:
    CODE_SIGN_IDENTITY = -
    SDKROOT = iphonesimulator10.0

=== CLEAN TARGET JSSAlertView OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET JSSAlertView OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
 -> JSSAlertView (3.0.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

[!] JSSAlertView did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.

/Users/syky/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:75:in `block in run'
/Users/syky/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:47:in `each'
/Users/syky/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:47:in `run'
/Users/syky/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/syky/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/syky/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/syky/.rbenv/versions/2.2.4/bin/pod:23:in `load'
/Users/syky/.rbenv/versions/2.2.4/bin/pod:23:in `<main>'
╭─syky at aluminium in ~/Desktop/test/JSSAlertView on swift3✔ using ‹2.2.4›
```

**Comment by syky27** [comment]
New version of cocoapods fixed this issue
